.Dd JANUARY 29, 2019
.Dt FULGURATE-RUN 1
.Os

.Sh NAME
.Nm fulgurate-run
.Nd run flashcards in the terminal

.Sh SYNOPSIS
.Nm
.Op Fl n Ar YYYY-MM-DD
.Op Fl R Ar NUM
.Op Fl N Ar NUM
.Op Fl r
.Op Fl b Ar NUM
.Op Fl f Ar CMD
.Op Fl F Ar CMD
.Ar CARDS-FILE
.Op Ar CARDS-FILE ...

.Sh DESCRIPTION
Runs one or more sets of flashcards interactively at the terminal. Cards
can be presented individually (the default) or in batches where several
cards will be presented before user feedback is required.
.Pp
The interaction for each card is as follows. The program first shows
the first (top) part of the card. Press any key after deciding on the
answer. The program then shows the second (bottom) part of the card. Press
~,1,2,3,4,5 for 0 through 5 respectively, indicating your evaluation of
how well you remembered the answer. 0 through 2 are failure responses
and 3 through 5 are success.

.Sh OPTIONS
.Bl -tag -width Ds
.It Fl n Ar YYYY-MM-DD
Set the current time. Defaults to the system clock.
.It Fl R Ar NUM
Set the maximum number of cards to review.
.It Fl N Ar NUM
Set the maximum number of new cards.
.It Fl r
Randomly order cards to review, from among all input card sets
.It Fl b Ar NUM
Enable batch mode and set the number of cards in one batch.
.It Fl f Ar CMD
Set a command to filter cards. It should take on stdin a sequence of
card data lines consisting of filename, first field, and second field,
separated by tabs. It should output to stdout new card data in the same
format, which will be shown instead of the original card data.
.It Fl F Ar CMD
Set a command to execute after a card's second field is shown. It should
take cards on stdin in the same format as the command for -f. Its output
is ignored.

.Sh EXIT STATUS
.Ex -std

.Sh SEE ALSO
.Xr fulgurate-show-schedule 1 ,
.Xr fulgurate-import 1 .

.Sh AUTHORS
.An Max Whitney
.An pranomostro Aq Mt pranomostro@posteo.net
